export const metadata = {
  title: "sucoding",
  description: "Generated by Next.js with npm",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    // ko로 하면 번역이 안뜸.
    <html lang="ko">
      <body>
        <main>{children}</main>
      </body>
    </html>
  );
}
